# Generated by Django 3.2.4 on 2021-06-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Art', '0003_alter_artwork_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='creator_IG',
            field=models.TextField(default='#'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='creator_email',
            field=models.TextField(default='#'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
