# Generated by Django 3.2.4 on 2021-07-11 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Art', '0006_alter_artwork_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='creator_email',
            field=models.TextField(default=''),
        ),
    ]
